esphome:
  name: emerson-charger
  friendly_name: batterie_r48
  min_version: 2025.10.1
  on_boot:
    priority: -100
    then:
      - delay: 100ms
      - logger.log: "Initialisation terminée, démarrage du bus CAN"
      - number.set:
          id: emerson_r48_output_voltage
          value: 48
      - number.set:
          id: emerson_r48_max_output_current
          value: 10
      - number.set:
          id: emerson_r48_max_input_current
          value: 6
      - switch.turn_on:
          id: emerson_r48_ac_sw
      - switch.turn_on:
          id: emerson_r48_dc_sw
      # Initialize sensors with default values to avoid "Unavailable" status
      - sensor.publish:
          id: r48_output_voltage
          state: 0.0
      - sensor.publish:
          id: r48_output_current
          state: 0.0

external_components:
  - source: 
      type: git
      url: https://github.com/jon7119/esphomeemerson-vertiv-r48
      ref: main
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esphome-Emerson-Jkbms"
    password: "123456789"

ota:
  - platform: esphome
    password: "123456789"
    
web_server:

spi:
  id: shared_spi
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

canbus:
  - platform: mcp2515
    id: can
    spi_id: shared_spi
    cs_pin: GPIO5
    can_id: 0x123
    bit_rate: 125kbps
    mode: NORMAL
    data_rate: 10Mhz

emerson_r48:
  id: emerson_r48_component
  canbus_id: can
  update_interval: 1s

time:
  - platform: sntp
    id: esphome_time
    servers: pool.ntp.org

switch:
  - platform: emerson_r48
    ac_sw:
      name: "R48 AC switch Turn OFF"
      id: emerson_r48_ac_sw
      restore_mode: ALWAYS_ON
    dc_sw:
      name: "R48 DC switch Turn OFF"
      id: emerson_r48_dc_sw
      restore_mode: ALWAYS_ON
    fan_sw:
      name: "R48 FAN switch MAX"
      id: emerson_r48_fan_sw
    led_sw:
      name: "R48 LED switch"
      id: emerson_r48_led_sw

binary_sensor:
  - platform: status
    name: "ESP Controller Status"

button:

  - platform: emerson_r48
    set_offline_values:
      name: "R48 Set offline values"

  - platform: restart
    name: "Restart ESP"

number:
  - platform: emerson_r48
    output_voltage:
      name: "R48 Set output voltage"
      id: emerson_r48_output_voltage
    max_output_current:
      name: "R48 Max output current"
      id: emerson_r48_max_output_current
      unit_of_measurement: '%'
    max_input_current:
      name: "R48 Max input current"
      id: emerson_r48_max_input_current

sensor:
  - platform: emerson_r48
    output_voltage:
      name: "R48 Output voltage"
      id: r48_output_voltage
    output_current:
      name: "R48 Output current"
      id: r48_output_current  
    output_temp:
      name: "R48 Temperature"
    input_voltage:
      name: "R48 AC Voltage"
    max_output_current:
      name: "R48 DC max current"
      unit_of_measurement: '%'

  - platform: template
    name: outPower
    id: outpower
    unit_of_measurement: W
    device_class: power
    update_interval: 6s 
    accuracy_decimals: 2
    lambda: |-
      if(id(r48_output_current).state is not None and id(r48_output_voltage).state is not None and id(r48_output_current).state>0) { 
        return ( id(r48_output_current).state * id(r48_output_voltage).state ); 
      } 
      else {return 0;}
