esphome:
  name: "esphome-emerson"
  friendly_name: Emerson_Vertiv_R48

external_components:
  - source: github://leodesigner/esphome-emerson-vertiv-r48
#    refresh: 0s

esp8266:
  board: esp01_1m

# Enable logging
logger:
#  level: DEBUG
#  logs:
#    canbus: INFO

# Enable Home Assistant API
#api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Emerson"
    password: "qwertyzxc"

ota:
  password: !secret ota_password

#web_server:
captive_portal:

mqtt:
  broker: !secret mqtt_host
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  id: mqtt_client
  topic_prefix: eh/emerson


spi:
  id: McpSpi
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

canbus:
  - platform: mcp2515
    id: can
    spi_id: McpSpi
    use_extended_id: true
    cs_pin: GPIO15
    can_id: 0x0607FF83
    bit_rate: 125kbps
    mode: NORMAL
    data_rate: 10Mhz


emerson_r48:
  canbus_id: can
  update_interval: 1s

sensor:
  - platform: emerson_r48
    output_voltage:
      name: Output voltage
    output_current:
      name: Output current
    output_temp:
      name: Temperature
    input_voltage:
      name: AC Voltage
    max_output_current:
      name: DC max current


number:
  - platform: emerson_r48
    output_voltage:
      name: Set output voltage
    max_output_current:
      name: Max output current
    max_input_current:
      name: Max input current

button:
  - platform: emerson_r48
    set_offline_values:
      name: Set offline values
  - platform: restart
    name: "Restart ESP"

switch:
  - platform: emerson_r48
    ac_sw:
      name: "AC switch Turn OFF"
    dc_sw:
      name: "DC switch Turn OFF"
    fan_sw:
      name: "FAN switch MAX"
    led_sw:
      name: "LED switch"

      